# Generated by Django 4.0.3 on 2022-05-12 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contactesports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.TextField(blank=True)),
                ('uemail', models.TextField(blank=True)),
                ('unumber', models.TextField(blank=True)),
                ('umessage', models.TextField(blank=True)),
            ],
        ),
    ]
