# Generated by Django 3.1.6 on 2022-06-30 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esportscentresys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.TextField(blank=True)),
                ('lastname', models.TextField(blank=True)),
                ('contactnumber', models.TextField(blank=True)),
                ('emailaddress', models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Contactesports',
        ),
    ]
